@TrainOffice_HostAddress = http://localhost:5091

GET {{TrainOffice_HostAddress}}/api/weatherforecast/
Accept: application/json

###

GET {{TrainOffice_HostAddress}}/api/trains/
Accept: application/json

###
